spring.application.name=backend

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/sduselfcheck
spring.datasource.username=vivek
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081